# action.yml
name: app-state-diagram-test
description: Produces a full application state diagram and hyperlinked documentation from ALPS profile
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  config:
    description: Config file
    required: false
  profile:
    description: Profile file
    required: false
    default: profile.xml
runs:
  using: docker
  image: 'ghcr.io/naokitsuchiya/asd-action:latest'
  args:
    - ${{ inputs.config }}
    - ${{ inputs.profile }}
